package formularios;

import connection.ConnectionFactory;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Emprestimos;
import model.dao.EmprestimoDAO;
import net.proteanit.sql.DbUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author lyand
 */
public class ConsultarEmprestimo extends javax.swing.JInternalFrame {

    public ConsultarEmprestimo() {
        initComponents();
        readJTable();
        setClosable(true);
    }

    public void setPosicao() { //Posiciona o JInternalFrame no centro do JFrame Principaç.
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void readJTable() { //Exibe os dados de Empréstimo na JTable.
        DefaultTableModel tblConsultExemp = (DefaultTableModel) tblConsultaEmp.getModel();
        tblConsultExemp.setNumRows(0);

        EmprestimoDAO emp_dao = new EmprestimoDAO();
        for (Emprestimos emps : emp_dao.read()) {
            tblConsultExemp.addRow(new Object[]{
                emps.getId(),
                emps.getNumChamada(),
                emps.getUsuario(),
                emps.getDataEmp(),
                emps.getDataDev(),
                emps.getDevolvido(),
                emps.getSituacao()
            });
        }
    }

    public void readJTableUsuario(String name) { //Exibe o resultado da pesquisa de empréstimo por usuário.
        DefaultTableModel tblConsultExemp = (DefaultTableModel) tblConsultaEmp.getModel();
        tblConsultExemp.setNumRows(0);

        EmprestimoDAO emp_dao = new EmprestimoDAO();
        for (Emprestimos emps : emp_dao.readNome(name)) {
            tblConsultExemp.addRow(new Object[]{
                emps.getId(),
                emps.getNumChamada(),
                emps.getUsuario(),
                emps.getDataEmp(),
                emps.getDataDev(),
                emps.getDevolvido(),
                emps.getSituacao()
            });
        }
    }

    public void readJTableChamada(String code) { //Exibe o resultado da pesquisa de empréstimo por nº de chamada.
        DefaultTableModel tblConsultExemp = (DefaultTableModel) tblConsultaEmp.getModel();
        tblConsultExemp.setNumRows(0);

        EmprestimoDAO emp_dao = new EmprestimoDAO();
        for (Emprestimos emps : emp_dao.readChamada(code)) {
            tblConsultExemp.addRow(new Object[]{
                emps.getId(),
                emps.getNumChamada(),
                emps.getUsuario(),
                emps.getDataEmp(),
                emps.getDataDev(),
                emps.getDevolvido(),
                emps.getSituacao()
            });
        }
    }

    //Efetua pesquisa de empréstimo por nome.
    public void pesquisaGeralEmprestimo() {
        Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;
        String sql = "SELECT id,numChamada,usuario,dataEmp,dataDev,devolvido,situacao FROM tbl_emp WHERE numChamada LIKE ? OR usuario LIKE ?";

        try {
            stmt = con.prepareStatement(sql);
            stmt.setString(1, "%" + pesqEmprestimo.getText() + "%");
            stmt.setString(2, "%" + pesqEmprestimo.getText() + "%");
            rs = stmt.executeQuery();

            tblConsultaEmp.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao pesquisar empréstimo: " + ex);
        } finally {
            ConnectionFactory.closeConnection(con, stmt, rs);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cancelEmp = new javax.swing.JButton();
        lblLupaEmp = new javax.swing.JLabel();
        pesqEmprestimo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsultaEmp = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(700, 600));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Consultar Empréstimos");

        cancelEmp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cancelEmp.setText("Cancelar");
        cancelEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEmpActionPerformed(evt);
            }
        });

        lblLupaEmp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLupaEmp.setText("Usuário ou Nº de Chamada");

        pesqEmprestimo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pesqEmprestimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesqEmprestimoKeyReleased(evt);
            }
        });

        tblConsultaEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nº de Chamada", "Usuário", "Data Empréstimo", "Data Devolução", "Devolvido em", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblConsultaEmp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(cancelEmp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(269, 269, 269)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblLupaEmp)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(pesqEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLupaEmp)
                    .addComponent(pesqEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelEmp)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEmpActionPerformed
        doDefaultCloseAction();
    }//GEN-LAST:event_cancelEmpActionPerformed

    private void pesqEmprestimoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesqEmprestimoKeyReleased
        pesquisaGeralEmprestimo();
    }//GEN-LAST:event_pesqEmprestimoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLupaEmp;
    private javax.swing.JTextField pesqEmprestimo;
    private javax.swing.JTable tblConsultaEmp;
    // End of variables declaration//GEN-END:variables
}
