
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Emprestimos;
import model.dao.EmprestimoDAO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author lyand
 */
public class ConsultarEmprestimo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarEmprestimo
     */
    public ConsultarEmprestimo() {
        initComponents();
        readJTable();
        setClosable(true);
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    public void readJTable() {       
        DefaultTableModel tblConsultExemp = (DefaultTableModel) tblConsultaEmp.getModel();
        tblConsultExemp.setNumRows(0);
        
        EmprestimoDAO emp_dao = new EmprestimoDAO();
        for(Emprestimos emps: emp_dao.read()) {
            tblConsultExemp.addRow(new Object[]{
                emps.getId(),
                emps.getNumChamada(),
                emps.getUsuario(),
                emps.getDataEmp(),
                emps.getDataDev()
            });
        }
    }
    
    public void readJTableUsuario(String name) {       
        DefaultTableModel tblConsultExemp = (DefaultTableModel) tblConsultaEmp.getModel();
        tblConsultExemp.setNumRows(0);
        
        EmprestimoDAO emp_dao = new EmprestimoDAO();
        for(Emprestimos emps: emp_dao.readNome(name)) {
            tblConsultExemp.addRow(new Object[]{
                emps.getId(),
                emps.getNumChamada(),
                emps.getUsuario(),
                emps.getDataEmp(),
                emps.getDataDev()
            });
        }
    }
    
    public void readJTableChamada(String code) {       
        DefaultTableModel tblConsultExemp = (DefaultTableModel) tblConsultaEmp.getModel();
        tblConsultExemp.setNumRows(0);
        
        EmprestimoDAO emp_dao = new EmprestimoDAO();
        for(Emprestimos emps: emp_dao.readChamada(code)) {
            tblConsultExemp.addRow(new Object[]{
                emps.getId(),
                emps.getNumChamada(),
                emps.getUsuario(),
                emps.getDataEmp(),
                emps.getDataDev()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cancelEmp = new javax.swing.JButton();
        lblLupaEmp = new javax.swing.JLabel();
        pesqEmprestimo = new javax.swing.JTextField();
        btnPesqEmprestimo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsultaEmp = new javax.swing.JTable();
        selecionarCategoria = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(700, 600));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Consultar Empréstimos");

        cancelEmp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cancelEmp.setText("Cancelar");
        cancelEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEmpActionPerformed(evt);
            }
        });

        lblLupaEmp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLupaEmp.setText("Categoria");

        pesqEmprestimo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnPesqEmprestimo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPesqEmprestimo.setText("Pesquisar");
        btnPesqEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqEmprestimoActionPerformed(evt);
            }
        });

        tblConsultaEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nº de Chamada", "Usuário", "Data Empréstimo", "Data Devolução"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblConsultaEmp);

        selecionarCategoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        selecionarCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Nº de Chamada", "Usuário" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(cancelEmp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel1)
                        .addGap(0, 263, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLupaEmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecionarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesqEmprestimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesqEmprestimo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLupaEmp)
                    .addComponent(pesqEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesqEmprestimo)
                    .addComponent(selecionarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelEmp)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEmpActionPerformed
        doDefaultCloseAction();
    }//GEN-LAST:event_cancelEmpActionPerformed

    private void btnPesqEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqEmprestimoActionPerformed
        if (selecionarCategoria.getSelectedItem() == "Usuário") {
            if (pesqEmprestimo.getText().isBlank()) {
                JOptionPane.showMessageDialog(null, "Digite o Usuário desejado no campo de pesquisa.");
            } else {
                readJTableUsuario(pesqEmprestimo.getText());
            }
        } else if (selecionarCategoria.getSelectedItem() == "Nº de Chamada") {
            if (pesqEmprestimo.getText().isBlank()) {
                JOptionPane.showMessageDialog(null, "Digite o Nº de Chamada desejado no campo de pesquisa.");
            } else {
                readJTableChamada(pesqEmprestimo.getText());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma categoria para efetuar pesquisa.");
        }
    }//GEN-LAST:event_btnPesqEmprestimoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesqEmprestimo;
    private javax.swing.JButton cancelEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLupaEmp;
    private javax.swing.JTextField pesqEmprestimo;
    private javax.swing.JComboBox<String> selecionarCategoria;
    private javax.swing.JTable tblConsultaEmp;
    // End of variables declaration//GEN-END:variables
}
